export const GET_ERRORS = 'GET_ERRORS';
export const GET_ALL_LOCATIONS = 'GET_ALL_LOCATIONS';
export const ADD_NEW_LOCATION = 'ADD_NEW_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';